export const GET_ROCKETS = "GET_ROCKETS";
export const GET_PAST_ROCKETS = "GET_PAST_ROCKETS";
export const GET_UPCOMING_ROCKETS = "GET_UPCOMING_ROCKETS";
export const GET_ROCKETS_BY_DATE = "GET_ROCKETS_BY_DATE";
